name: hyp3-artraff-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - hyp3lib>=3,<4
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
